#pragma once

#define WRITE_ERROR "Eroare la write()\n"
#define READ_ERROR "Eroare la read()\n"
#define CLOSE_ERROR "Eroare la close()\n"
#define FORK_ERROR "Eroare la fork()\n"
#define OPEN_ERROR "Eroare la open()\n"
#define PIPE_ERROR "Eroare la pipe()\n"
#define SOCKET_ERROR "Eroare la socket()\n"
#define MKFIFO_ERROR "Eroare la MkFifo()\n"
#define CREATE_ERROR "Eroare la crearea fisierului()\n"
#define FOPEN_ERROR "Eroare la FOpen()\n"
#define READDIR_ERROR "Eroare la readdir()\n"
#define STAT_ERROR "Eroare la stat()\n"
#define ACCESS_ERROR "Eroare la access()\n"
#define READ_FILE_ERROR "Eroare la readfile()\n"
#define CONNECT_ERROR "Eroare la connect()\n"
#define WRITE_TO_SERVER_ERROR "Eroare la write() spre server.\n"
#define READ_TO_SERVER_ERROR "Eroare la read() de la server.\n"